package com.jeco.ui.controler;

public enum EnumNomeBotoes {
	CADASTRO_USUARIO,
	CADASTRO_USUARIO_CLOSE,
	CADASTRO_OVINO,
	CADASTRO_OVINO_CLOSE,
	CADASTRO_PESO,
	CADASTRO_PESO_CLOSE,
	CADASTRO_TIPO_OCORRENCIA,
	CADASTRO_TIPO_OCORRENCIA_CLOSE,
	CADASTRO_OCORRENCIA,
	CADASTRO_OCORRENCIA_CLOSE,
	CADASTRO_RACA,
	CADASTRO_RACA_CLOSE,
	VISUALIZAR_OVINOS,
	VISUALIZAR_OVINOS_CLOSE,
	VISUALIZAR_OCORRENCIAS,
	VISUALIZAR_OCORRENCIAS_CLOSE,
	VISUALIZAR_PESO,
	VISUALIZAR_PESO_CLOSE,
	VISUALIZAR_EVENTOS,
	VISUALIZAR_EVENTOS_CLOSE,	
	OPCAO_NULL,
	EXIT,
	LOGOFF,
	BACKUP,
	BACKUP_CLOSE
	
	

}
